# Generated by Django 4.2.5 on 2025-03-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=100)),
                ('usr_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
